Feature/bend 004
khasang/bend pull request #10
Opened 2019-03-05 10:08 UTC by Benderbej

REST layer for Place Entity

2019-03-06 17:40 UTC, SKuznet reviewed
.gradle - should be at ignore

2019-03-06 17:42 UTC, SKuznet requested changes

2019-03-06 17:42 UTC, SKuznet commented on src/main/java/io/khasang/bend/entity/Place.java
> +    private int album_id;//TODO with table albums??
fix comments

2019-03-10 09:37 UTC, Benderbej commented
I have changed both 003 and 004 branches, commited and pushed this branches. What should I do then? Do I need restart pull request? or this new commits automatically changed in this pull request allready, and I have nothing to do else?

2019-03-13 18:04 UTC, Benderbej commented
rm - r .gradle from git

2019-03-15 18:11 UTC, SKuznet approved these changes

2019-03-15 18:21 UTC, merged